version: '3.8'

services:
  #service php
  php:
    build: './php_docker'
    env_file:
      - .env
    volumes:
      - ./www/:/var/www/html

  # service apache
  apache:
    build: './apache_docker'
    depends_on:
      - php
    ports:
      - '8080:80'
    volumes:
      - ./www/:/var/www/html

  # service mariadb
  mariadb:
    image: mariadb:11.2
    ports:
      - '3308:3306'
    env_file:
      - .env
    volumes:
      - hsrdatabase:/var/lib/mysql

  # service phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  hsrdatabase: